apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ template "zookeeper.namespace" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.service.headless.annotations }}
  annotations:
    {{- if .Values.service.headless.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.service.headless.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: {{ .Values.service.headless.publishNotReadyAddresses }}
  ports:
<<<<<<< HEAD
    {{ if not .Values.service.disableBaseClientPort }}
    - name: tcp-client
      port: {{ .Values.service.port }}
      targetPort: client
    {{ end }}
    {{ if .Values.tls.client.enabled }}
    - name: tcp-client-tls
      port: {{ .Values.service.tlsClientPort }}
      targetPort: client-tls
    {{ end }}
    - name: follower
      port: {{ .Values.service.followerPort }}
      targetPort: follower
    - name: tcp-election
      port: {{ .Values.service.electionPort }}
=======
    {{- if not .Values.service.disableBaseClientPort }}
    - name: tcp-client
      port: {{ .Values.service.ports.client }}
      targetPort: client
    {{- end }}
    {{- if .Values.tls.client.enabled }}
    - name: tcp-client-tls
      port: {{ .Values.service.ports.tls }}
      targetPort: client-tls
    {{- end }}
    - name: tcp-follower
      port: {{ .Values.service.ports.follower }}
      targetPort: follower
    - name: tcp-election
      port: {{ .Values.service.ports.election }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
      targetPort: election
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
