annotations:
  category: Analytics
apiVersion: v2
<<<<<<< HEAD
appVersion: 7.14.1
=======
appVersion: 8.3.3
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: Kibana is an open source, browser based analytics and search dashboard for Elasticsearch. Kibana strives to be easy to get started with, while also being flexible and powerful.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/kibana
icon: https://bitnami.com/assets/stacks/kibana/img/kibana-stack-220x234.png
keywords:
  - kibana
  - analytics
  - monitoring
  - metrics
  - logs
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: kibana
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/kibana
  - https://www.elastic.co/products/kibana
<<<<<<< HEAD
version: 9.0.1
=======
version: 10.2.0
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
