annotations:
  category: DeveloperTools
apiVersion: v2
<<<<<<< HEAD
appVersion: 2.8.2
=======
appVersion: 2.9.4
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
dependencies:
  - condition: rabbitmq.enabled
    name: rabbitmq
    repository: https://charts.bitnami.com/bitnami
    version: 10.x.x
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    tags:
      - dataflow-database
    version: 11.x.x
  - condition: kafka.enabled
    name: kafka
    repository: https://charts.bitnami.com/bitnami
<<<<<<< HEAD
    version: 14.x.x
=======
    version: 18.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
description: Spring Cloud Data Flow is a microservices-based toolkit for building streaming and batch data processing pipelines in Cloud Foundry and Kubernetes.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/spring-cloud-dataflow
icon: https://bitnami.com/assets/stacks/spring-cloud-dataflow/img/spring-cloud-dataflow-stack-220x234.png
keywords:
  - spring-cloud
  - dataflow
  - skipper
  - spring
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: spring-cloud-dataflow
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/spring-cloud-dataflow
  - https://github.com/bitnami/containers/tree/main/bitnami/spring-cloud-skipper
  - https://dataflow.spring.io/
<<<<<<< HEAD
version: 4.0.3
=======
version: 12.1.0
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
