annotations:
  category: Infrastructure
apiVersion: v2
<<<<<<< HEAD
appVersion: 1.18.1
=======
appVersion: 1.22.0
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: Contour is an open source Kubernetes ingress controller that works by deploying the Envoy proxy as a reverse proxy and load balancer.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/contour
icon: https://bitnami.com/assets/stacks/contour/img/contour-stack-220x234.png
keywords:
  - ingress
  - envoy
  - contour
maintainers:
  - name: cellebyte
    url: https://github.com/Cellebyte
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: contour
sources:
  - https://github.com/projectcontour/contour
  - https://github.com/envoyproxy/envoy
  - https://github.com/bitnami/containers/tree/main/bitnami/contour
  - https://projectcontour.io
<<<<<<< HEAD
version: 5.5.1
=======
version: 9.1.0
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
