apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
=======
  name: {{ include "jupyterhub.hub.name" . }}
  namespace: {{ .Release.Namespace | quote }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: hub
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
<<<<<<< HEAD
  name: {{ include "jupyterhub.hub.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.hub.service.type }}
  {{- if (or (eq .Values.hub.service.type "LoadBalancer") (eq .Values.hub.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.hub.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{ if eq .Values.hub.service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.hub.service.loadBalancerSourceRanges }}
  {{ end }}
  {{- if (and (eq .Values.hub.service.type "LoadBalancer") (not (empty .Values.hub.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.hub.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.hub.service.port }}
      targetPort: http
      protocol: TCP
      {{- if (and (or (eq .Values.hub.service.type "NodePort") (eq .Values.hub.service.type "LoadBalancer")) (not (empty .Values.hub.service.nodePorts.http))) }}
=======
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.hub.service.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.hub.service.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.hub.service.type }}
  {{- if and .Values.hub.service.clusterIP (eq .Values.hub.service.type "ClusterIP") }}
  clusterIP: {{ .Values.hub.service.clusterIP }}
  {{- end }}
  {{- if or (eq .Values.hub.service.type "LoadBalancer") (eq .Values.hub.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.hub.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.hub.service.type "LoadBalancer") (not (empty .Values.hub.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.hub.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.hub.service.type "LoadBalancer") (not (empty .Values.hub.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.hub.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.hub.service.sessionAffinity }}
  sessionAffinity: {{ .Values.hub.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.hub.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.hub.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: {{ coalesce .Values.hub.service.ports.http .Values.hub.service.port }}
      targetPort: http
      protocol: TCP
      {{- if and (or (eq .Values.hub.service.type "NodePort") (eq .Values.hub.service.type "LoadBalancer")) (not (empty .Values.hub.service.nodePorts.http)) }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
      nodePort: {{ .Values.hub.service.nodePorts.http }}
      {{- else if eq .Values.hub.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
<<<<<<< HEAD
=======
    {{- if .Values.hub.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.hub.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: hub
