<<<<<<< HEAD
{{- if and .Values.configuration.google (not .Values.configuration.google.existingSecret) }}
=======
{{- if and .Values.configuration.google.enabled (not .Values.configuration.google.existingSecret) }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-google
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: oauth2-proxy
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  service-account.json: {{ include "common.tplvalues.render" ( dict "value" .Values.configuration.google.serviceAccountJson "context" $ ) | b64enc | quote }}
{{- end -}}
