<<<<<<< HEAD
{{- if (include "cassandra.createTlsSecret" . )}}
{{- $ca := genCA "cassandra-ca" 365 }}
{{- $fullname := include "common.names.fullname" . }}
{{- $releaseNamespace := .Release.Namespace }}
{{- $clusterDomain := .Values.clusterDomain }}
{{- $serviceName := include "common.names.fullname" . }}
{{- $headlessServiceName := printf "%s-headless" (include "common.names.fullname" .) }}
{{- $altNames := list (printf "*.%s.%s.svc.%s" $serviceName $releaseNamespace $clusterDomain) (printf "%s.%s.svc.%s" $serviceName $releaseNamespace $clusterDomain) (printf "*.%s.%s.svc.%s" $headlessServiceName $releaseNamespace $clusterDomain) (printf "%s.%s.svc.%s" $headlessServiceName $releaseNamespace $clusterDomain) "localhost" "127.0.0.1" $fullname }}
{{- $crt := genSignedCert $fullname nil $altNames 365 $ca }}
=======
<<<<<<<< HEAD:bitnami/cassandra/templates/tls-secret.yaml
{{- if (include "cassandra.createTlsSecret" . ) }}

{{- $tlsCertStr := regexSplit "###" (include "cassandra.getTlsCertStrFromSecret" .) -1 }}
{{- $ca := index $tlsCertStr 0 }}
{{- $crt := index $tlsCertStr 1 }}
{{- $key := index $tlsCertStr 2 }}

========
{{- if eq (include "harbor.autoGenCertForIngress" .) "true" }}
{{- $ca := genCA "harbor-ca" 365 }}
{{- $cert := genSignedCert .Values.ingress.hosts.core nil (list .Values.ingress.hosts.core ) 365 $ca }}
>>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0:bitnami/harbor/templates/ingress/secret.yaml
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-crt
<<<<<<< HEAD
=======
  namespace: {{ .Release.Namespace | quote }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
<<<<<<< HEAD
  ca.crt: {{ $ca.Cert | b64enc | quote }}
  tls.crt: {{ $crt.Cert | b64enc | quote }}
  tls.key: {{ $crt.Key | b64enc | quote }}
=======
<<<<<<<< HEAD:bitnami/cassandra/templates/tls-secret.yaml
  ca.crt: {{ $ca | b64enc | quote }}
  tls.crt: {{ $crt | b64enc | quote }}
  tls.key: {{ $key | b64enc | quote }}
========
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
---
{{- $cert := genSignedCert .Values.ingress.hosts.notary nil (list .Values.ingress.hosts.notary) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor.ingress-notary" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
>>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0:bitnami/harbor/templates/ingress/secret.yaml
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
{{- end }}
