annotations:
  category: Database
apiVersion: v2
<<<<<<< HEAD
appVersion: 8.0.26
=======
appVersion: 8.0.30
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: MySQL is a fast, reliable, scalable, and easy to use open source relational database system. Designed to handle mission-critical, heavy-load production applications.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/mysql
icon: https://bitnami.com/assets/stacks/mysql/img/mysql-stack-220x234.png
keywords:
  - mysql
  - database
  - sql
  - cluster
  - high availability
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: mysql
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/mysql
  - https://mysql.com
<<<<<<< HEAD
version: 8.8.6
=======
version: 9.3.0
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
