apiVersion: v1
kind: Service
metadata:
  name: {{ template "grafana-tempo.ingester.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: ingester
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.ingester.service.annotations }}
  annotations:
    {{- if .Values.ingester.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.ingester.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.ingester.service.type }}
<<<<<<< HEAD
  {{- if .Values.ingester.service.clusterIP }}
  clusterIP: {{ .Values.ingester.service.clusterIP }}
  {{- end }}
  {{- if (or (eq .Values.ingester.service.type "LoadBalancer") (eq .Values.ingester.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.ingester.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{ if eq .Values.ingester.service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.ingester.service.loadBalancerSourceRanges }}
  {{ end }}
  {{- if (and (eq .Values.ingester.service.type "LoadBalancer") (not (empty .Values.ingester.service.loadBalancerIP))) }}
=======
  {{- if .Values.ingester.service.sessionAffinity }}
  sessionAffinity: {{ .Values.ingester.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.ingester.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.ingester.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if and .Values.ingester.service.clusterIP (eq .Values.ingester.service.type "ClusterIP") }}
  clusterIP: {{ .Values.ingester.service.clusterIP }}
  {{- end }}
  {{- if or (eq .Values.ingester.service.type "LoadBalancer") (eq .Values.ingester.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.ingester.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.ingester.service.type "LoadBalancer") (not (empty .Values.ingester.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.ingester.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.ingester.service.type "LoadBalancer") (not (empty .Values.ingester.service.loadBalancerIP)) }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
  loadBalancerIP: {{ .Values.ingester.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http
<<<<<<< HEAD
      port: {{ .Values.ingester.service.port }}
=======
      port: {{ .Values.ingester.service.ports.http }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
      targetPort: http
      protocol: TCP
      {{- if (and (or (eq .Values.ingester.service.type "NodePort") (eq .Values.ingester.service.type "LoadBalancer")) (not (empty .Values.ingester.service.nodePorts.http))) }}
      nodePort: {{ .Values.ingester.service.nodePorts.http }}
      {{- else if eq .Values.ingester.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    - name: grpc
<<<<<<< HEAD
      port: {{ .Values.ingester.service.grpcPort }}
=======
      port: {{ .Values.ingester.service.ports.grpc }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
      targetPort: grpc
      protocol: TCP
      {{- if (and (or (eq .Values.ingester.service.type "NodePort") (eq .Values.ingester.service.type "LoadBalancer")) (not (empty .Values.ingester.service.nodePorts.grpc))) }}
      nodePort: {{ .Values.ingester.service.nodePorts.grpc }}
      {{- else if eq .Values.ingester.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
<<<<<<< HEAD
=======
    {{- if .Values.ingester.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.ingester.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: ingester
