{{- if and .Values.core.configOverwriteJson (not .Values.core.configOverwriteJsonSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-config-override" (include "harbor.core" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: core
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
<<<<<<< HEAD:bitnami/solr/templates/secret.yaml
  {{ if .Values.authentication.adminPassword }}
  solr-password: {{ .Values.authentication.adminPassword | b64enc | quote }}
  {{ else }}
  solr-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
---
{{- end }}
{{- if and .Values.tls.enabled (not .Values.tls.passwordsSecretName) (or .Values.tls.keystorePassword .Values.tls.truststorePassword .Values.tls.autoGenerated) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-tls-pass" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if or .Values.tls.keystorePassword .Values.tls.autoGenerated }}
  tls-keystore-password: {{ (.Values.tls.keystorePassword | default (randAlphaNum 10)) | b64enc | quote }}
  {{- end }}
  {{- if or .Values.tls.truststorePassword .Values.tls.autoGenerated }}
  tls-truststore-password: {{ (.Values.tls.truststorePassword | default (randAlphaNum 10))| b64enc | quote }}
  {{- end }}
---
=======
  overrides.json: {{ include "common.tplvalues.render" ( dict "value" .Values.core.configOverwriteJson "context" $ ) | b64enc | quote }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0:bitnami/harbor/templates/core/core-config-override-secret.yaml
{{- end }}
