<<<<<<< HEAD
{{- if or (not .Values.existingSecret) (and (not .Values.smtpExistingSecret) .Values.smtpPassword) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "odoo.fullname" . }}
=======
{{- if or (not .Values.existingSecret) (and .Values.smtpPassword (not .Values.smtpExistingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if not .Values.existingSecret }}
<<<<<<< HEAD
  {{- if .Values.odooPassword }}
  odoo-password: {{ .Values.odooPassword | b64enc | quote }}
  {{- else }}
  odoo-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if and .Values.smtpPassword (not .Values.smtpExistingSecret) }}
  {{- if .Values.smtpPassword }}
=======
  odoo-password: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "odoo-password" "length" 10 "providedValues" (list "odooPassword") "context" $) }}
  {{- end }}
  {{- if and .Values.smtpPassword (not .Values.smtpExistingSecret) }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
  smtp-password: {{ .Values.smtpPassword | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
