annotations:
  category: CRM
apiVersion: v2
<<<<<<< HEAD
appVersion: 7.11.21
=======
appVersion: 7.12.7
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: SuiteCRM is a completely open source, enterprise-grade Customer Relationship Management (CRM) application. SuiteCRM is a fork of the popular SugarCRM application.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/suitecrm
icon: https://bitnami.com/assets/stacks/suitecrm/img/suitecrm-stack-220x234.png
keywords:
  - suitecrm
  - crm
  - http
  - web
  - php
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: suitecrm
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/suitecrm
  - https://www.suitecrm.com/
<<<<<<< HEAD
version: 9.3.21
=======
version: 11.2.0
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
