<<<<<<< HEAD
{{- if not .Values.mariadb.enabled }}
=======
{{- if and (not .Values.mariadb.enabled) (not .Values.externalDatabase.existingSecret) }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "common.names.fullname" . }}-externaldb"
<<<<<<< HEAD
=======
  namespace: {{ .Release.Namespace | quote }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ default "" .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
