annotations:
  category: CMS
apiVersion: v2
<<<<<<< HEAD
appVersion: 9.2.5
=======
appVersion: 9.4.5
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: Drupal is one of the most versatile open source content management systems in the world. It is pre-configured with the Ctools and Views modules, Drush and Let's Encrypt auto-configuration support.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/drupal
icon: https://bitnami.com/assets/stacks/drupal/img/drupal-stack-220x234.png
keywords:
  - drupal
  - cms
  - blog
  - http
  - web
  - application
  - php
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: drupal
sources:
<<<<<<< HEAD
  - https://github.com/bitnami/bitnami-docker-drupal
  - http://www.drupal.org/
version: 10.2.34
=======
  - https://github.com/bitnami/containers/tree/main/bitnami/drupal
  - https://www.drupal.org/
version: 12.4.0
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
