{{- if (include "discourse.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-discourse" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
<<<<<<< HEAD
  {{- if and (.Values.discourse.password) (not .Values.discourse.existingSecret) }}
  discourse-password: {{ .Values.discourse.password | b64enc | quote }}
  {{- else if not .Values.discourse.existingSecret }}
  discourse-password: {{ randAlphaNum 10 | b64enc | quote }}
=======
  {{- if not .Values.auth.existingSecret }}
  discourse-password: {{ include "common.secrets.passwords.manage" (dict "secret" (printf "%s-discourse" (include "common.names.fullname" .)) "key" "discourse-password" "providedValues" (list "auth.password") "context" $) }}
  {{- end }}
  {{- if and .Values.smtp.enabled .Values.smtp.password (not .Values.smtp.existingSecret) }}
  smtp-password: {{ .Values.smtp.password | b64enc | quote }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
  {{- end }}
  {{- if and (.Values.discourse.smtp.password) (.Values.discourse.smtp.enabled) (not .Values.discourse.smtp.existingSecret) }}
  smtp-password: {{ .Values.discourse.smtp.password | b64enc | quote }}
  {{- end }}
{{- end }}
