{{- if and .Values.forwarder.enabled .Values.forwarder.rbac.create }}
kind: ClusterRoleBinding
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
metadata:
<<<<<<< HEAD
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ template "common.names.fullname" . }}
=======
  name: {{ include "common.names.fullname.namespace" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ template "common.names.fullname.namespace" . }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
subjects:
  - kind: ServiceAccount
    name: {{ template "fluentd.forwarder.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
