<<<<<<< HEAD
{{- range .Values.apprepository.initialRepos }}
{{- if or .caCert .authorizationHeader }}
=======
{{- if .Values.packaging.helm.enabled }}
{{- range .Values.apprepository.initialRepos }}
{{- if or .caCert .authorizationHeader .basicAuth }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "apprepo-%s-secrets" .name }}
<<<<<<< HEAD
  {{- if .namespace }}
  namespace: {{ .namespace | quote }}
  {{- else }}
  namespace: {{ $.Release.Namespace | quote }}
  {{- end }}
=======
  namespace: {{ default (include "kubeapps.globalReposNamespace" $) .namespace | quote }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    {{- if $.Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- if .caCert }}
  ca.crt: |-
    {{ .caCert | b64enc }}
  {{- end }}
<<<<<<< HEAD
  {{- if .authorizationHeader }}
  authorizationHeader: |-
    {{ .authorizationHeader | b64enc }}
  {{- end }}
---
{{/* credentials are required in the release namespace for syncer jobs */}}
{{- if .namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-apprepo-%s" .namespace .name }}
=======
  {{- $authorizationHeader := "" }}
  {{- if .authorizationHeader }}
    {{- $authorizationHeader = .authorizationHeader }}
  {{- else if .basicAuth }}
    {{- $authorizationHeader = printf "Basic %s" (printf "%s:%s" .basicAuth.user .basicAuth.password | b64enc) }}
  {{- end }}
  {{- if $authorizationHeader }}
  authorizationHeader: |-
    {{ $authorizationHeader | b64enc }}
  {{- end }}
---
{{/* credentials are required in the release namespace for syncer jobs */}}
{{- if or .namespace $.Values.apprepository.globalReposNamespaceSuffix }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-apprepo-%s" (default (include "kubeapps.globalReposNamespace" $) .namespace) .name }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    {{- if $.Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- if .caCert }}
  ca.crt: |-
    {{ .caCert | b64enc }}
  {{- end }}
<<<<<<< HEAD
  {{- if .authorizationHeader }}
  authorizationHeader: |-
    {{ .authorizationHeader | b64enc }}
=======
  {{- if $authorizationHeader }}
  authorizationHeader: |-
    {{ $authorizationHeader | b64enc }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
<<<<<<< HEAD
=======
{{- end }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
