annotations:
  category: MachineLearning
apiVersion: v2
<<<<<<< HEAD
appVersion: 1.4.2
dependencies:
=======
appVersion: 1.5.0
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
<<<<<<< HEAD
    version: 1.x.x
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    version: 10.x.x
description: JupyterHub brings the power of notebooks to groups of users. It gives users access to computational environments and resources without burdening the users with installation and maintenance tasks
=======
    version: 2.x.x
description: JupyterHub brings the power of notebooks to groups of users. It gives users access to computational environments and resources without burdening the users with installation and maintenance tasks.
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
engine: gotpl
home: https://jupyter.org/hub
icon: https://bitnami.com/assets/stacks/jupyterhub/img/jupyterhub-stack-220x234.png
keywords:
  - python
  - scientific
maintainers:
<<<<<<< HEAD
  - email: containers@bitnami.com
    name: Bitnami
name: jupyterhub
sources:
  - https://github.com/bitnami/bitnami-docker-jupyterhub
  - https://github.com/jupyterhub/jupyterhub
version: 0.1.18
=======
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: jupyterhub
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/jupyterhub
  - https://github.com/jupyterhub/jupyterhub
version: 1.4.0
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
