annotations:
  category: DeveloperTools
apiVersion: v2
<<<<<<< HEAD
appVersion: 1.10.2
=======
appVersion: 1.13.1
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: HashiCorp Consul is a tool for discovering and configuring services in your infrastructure.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/consul
icon: https://bitnami.com/assets/stacks/consul/img/consul-stack-220x234.png
keywords:
  - discovering
  - configuring
  - services
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: consul
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/consul
  - https://www.consul.io/
<<<<<<< HEAD
version: 9.3.5
=======
version: 10.8.0
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
