{{- if and .Values.envoy.enabled .Values.envoy.autoscaling.enabled (eq .Values.envoy.kind "deployment") }}
<<<<<<< HEAD
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "common.names.fullname" . }}-envoy
  namespace: {{ .Release.Namespace | quote }}
=======
apiVersion: {{ include "common.capabilities.hpa.apiVersion" ( dict "context" $ ) }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ printf "%s-envoy" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: envoy
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
    kind: Deployment
<<<<<<< HEAD
    name: {{ include "common.names.fullname" . }}-envoy
=======
    name: {{ printf "%s-envoy" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
  minReplicas: {{ .Values.envoy.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.envoy.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.envoy.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
<<<<<<< HEAD
        targetAverageUtilization: {{ .Values.envoy.autoscaling.targetCPU }}
=======
        {{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .) }}
        targetAverageUtilization: {{ .Values.envoy.autoscaling.targetCPU }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.envoy.autoscaling.targetCPU }}
        {{- end }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
    {{- end }}
    {{- if .Values.envoy.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
<<<<<<< HEAD
        targetAverageUtilization: {{ .Values.envoy.autoscaling.targetMemory }}
=======
        {{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .) }}
        targetAverageUtilization: {{ .Values.envoy.autoscaling.targetMemory }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.envoy.autoscaling.targetMemory }}
        {{- end }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
    {{- end }}
{{- end }}
