{{- if (include "kafka.createJaasSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-jaas" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if (include "kafka.client.saslAuthentication" .) }}
<<<<<<< HEAD
  {{- $clientUsers := coalesce .Values.auth.sasl.jaas.clientUsers .Values.auth.jaas.clientUsers }}
  {{- $clientPasswords := coalesce .Values.auth.sasl.jaas.clientPasswords .Values.auth.jaas.clientPasswords }}
=======
  {{- $clientUsers := .Values.auth.sasl.jaas.clientUsers }}
  {{- $clientPasswords := .Values.auth.sasl.jaas.clientPasswords }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
  {{- if $clientPasswords }}
  client-passwords: {{ join "," $clientPasswords | b64enc | quote }}
  system-user-password: {{ index $clientPasswords 0 | b64enc | quote }}
  {{- else }}
  {{- $passwords := list }}
  {{- range $clientUsers }}
  {{- $passwords = append $passwords (randAlphaNum 10) }}
  {{- end }}
  client-passwords: {{ join "," $passwords | b64enc | quote }}
  system-user-password: {{ index $passwords 0 | b64enc | quote }}
  {{- end }}
  {{- end }}
<<<<<<< HEAD
  {{- $zookeeperUser := coalesce .Values.auth.sasl.jaas.zookeeperUser .Values.auth.jaas.zookeeperUser }}
  {{- if and .Values.zookeeper.auth.enabled $zookeeperUser }}
  {{- $zookeeperPassword := coalesce .Values.auth.sasl.jaas.zookeeperPassword .Values.auth.jaas.zookeeperPassword }}
  zookeeper-password: {{ default (randAlphaNum 10) $zookeeperPassword | b64enc | quote }}
  {{- end }}
  {{- if (include "kafka.interBroker.saslAuthentication" .) }}
  {{- $interBrokerPassword := coalesce .Values.auth.sasl.jaas.interBrokerPassword .Values.auth.jaas.interBrokerPassword }}
=======
  {{- $zookeeperUser := .Values.auth.sasl.jaas.zookeeperUser }}
  {{- if and .Values.zookeeper.auth.client.enabled $zookeeperUser }}
  {{- $zookeeperPassword := .Values.auth.sasl.jaas.zookeeperPassword }}
  zookeeper-password: {{ default (randAlphaNum 10) $zookeeperPassword | b64enc | quote }}
  {{- end }}
  {{- if (include "kafka.interBroker.saslAuthentication" .) }}
  {{- $interBrokerPassword := .Values.auth.sasl.jaas.interBrokerPassword }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
  inter-broker-password: {{ default (randAlphaNum 10) $interBrokerPassword | b64enc | quote }}
  {{- end }}
{{- end }}
