annotations:
  category: Database
apiVersion: v2
<<<<<<< HEAD
appVersion: 10.5.12
=======
appVersion: 10.6.9
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: MariaDB is an open source, community-developed SQL database server that is widely in use around the world due to its enterprise features, flexibility, and collaboration with leading tech firms.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/mariadb
icon: https://bitnami.com/assets/stacks/mariadb/img/mariadb-stack-220x234.png
keywords:
  - mariadb
  - mysql
  - database
  - sql
  - prometheus
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: mariadb
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/mariadb
  - https://github.com/prometheus/mysqld_exporter
  - https://mariadb.org
<<<<<<< HEAD
version: 9.5.0
=======
version: 11.2.0
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
