<<<<<<< HEAD
=======
{{- if .Values.kubeops.enabled }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubeapps.kubeops.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: kubeops
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.kubeops.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.kubeops.service.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.kubeops.service.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
<<<<<<< HEAD
    - port: {{ .Values.kubeops.service.port }}
=======
    - port: {{ .Values.kubeops.service.ports.http }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: kubeops
<<<<<<< HEAD
=======
{{- end }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
