annotations:
  category: E-Learning
apiVersion: v2
<<<<<<< HEAD
appVersion: 3.11.2
=======
appVersion: 4.0.3
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.x.x
<<<<<<< HEAD
description: Moodle&trade; is a learning platform designed to provide educators, administrators and learners with a single robust, secure and integrated system to create personalised learning environments
=======
description: Moodle(TM) LMS is an open source online Learning Management System widely used at universities, schools, and corporations. It is modular and highly adaptable to any type of online learning.
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/moodle
icon: https://bitnami.com/assets/stacks/moodle/img/moodle-stack-220x234.png
keywords:
  - moodle
  - learning
  - php
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: moodle
sources:
<<<<<<< HEAD
  - https://github.com/bitnami/bitnami-docker-moodle
  - http://www.moodle.org/
version: 11.0.25
=======
  - https://github.com/bitnami/containers/tree/main/bitnami/moodle
  - https://www.moodle.org/
version: 14.1.17
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
