annotations:
  category: Database
apiVersion: v2
<<<<<<< HEAD
appVersion: 11.13.0
=======
appVersion: 14.5.0
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: This PostgreSQL cluster solution includes the PostgreSQL replication manager, an open-source tool for managing replication and failover on PostgreSQL clusters.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha
icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
keywords:
  - postgresql
  - repmgr
  - pgpool
  - postgres
  - database
  - sql
  - replication
  - cluster
  - high availability
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: postgresql-ha
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/postgresql
  - https://www.postgresql.org/
<<<<<<< HEAD
version: 7.9.2
=======
version: 9.4.0
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
