annotations:
  category: Analytics
apiVersion: v2
<<<<<<< HEAD
appVersion: 0.50.0
=======
appVersion: 0.58.0
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
dependencies:
  - condition: exporters.enabled,exporters.node-exporter.enabled
    name: node-exporter
    repository: https://charts.bitnami.com/bitnami
    version: 3.x.x
  - condition: exporters.enabled,exporters.kube-state-metrics.enabled
    name: kube-state-metrics
    repository: https://charts.bitnami.com/bitnami
<<<<<<< HEAD
    version: 2.x.x
description: kube-prometheus collects Kubernetes manifests to provide easy to operate end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus Operator.
=======
    version: 3.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: Prometheus Operator provides easy monitoring definitions for Kubernetes services and deployment and management of Prometheus instances.
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/kube-prometheus
icon: https://bitnami.com/assets/stacks/prometheus-operator/img/prometheus-operator-stack-220x234.png
keywords:
  - prometheus
  - alertmanager
  - operator
  - monitoring
kubeVersion: '>= 1.16.0-0'
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: kube-prometheus
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/prometheus-operator
  - https://github.com/bitnami/containers/tree/main/bitnami/prometheus
  - https://github.com/bitnami/containers/tree/main/bitnami/alertmanager
  - https://github.com/prometheus-operator/kube-prometheus
<<<<<<< HEAD
version: 6.1.8
=======
version: 8.1.0
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
