annotations:
  category: Infrastructure
apiVersion: v2
<<<<<<< HEAD
appVersion: 5.1.1
=======
appVersion: 5.2.0
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
dependencies:
  - condition: db.bundleTestDB
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    tags:
      - phpmyadmin-database
    version: 11.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: phpMyAdmin is a free software tool written in PHP, intended to handle the administration of MySQL over the Web. phpMyAdmin supports a wide range of operations on MySQL and MariaDB.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/phpmyadmin
icon: https://bitnami.com/assets/stacks/phpmyadmin/img/phpmyadmin-stack-220x234.png
keywords:
  - mariadb
  - mysql
  - phpmyadmin
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: phpmyadmin
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/phpmyadmin
  - https://www.phpmyadmin.net/
<<<<<<< HEAD
version: 8.2.12
=======
version: 10.2.4
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
