{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
<<<<<<< HEAD
=======
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  ingress:
    # Allow inbound connections
    - ports:
        - port: {{ .Values.service.ports.epmd }}  # EPMD
        - port: {{ .Values.service.ports.amqp }}
        - port: {{ .Values.service.ports.amqpTls }}
        - port: {{ .Values.service.ports.dist }}
        - port: {{ .Values.service.ports.manager }}
      {{- if not .Values.networkPolicy.allowExternal }}
      from:
        - podSelector:
            matchLabels:
              {{ printf "%s-client" (include "common.names.fullname" .) }}: "true"
        - podSelector:
            matchLabels:
              {{- include "common.labels.matchLabels" . | nindent 14 }}
        {{- if .Values.networkPolicy.additionalRules }}
        {{- include "common.tplvalues.render" (dict "value" .Values.networkPolicy.additionalRules "context" $) | nindent 8 }}
        {{- end }}
      {{- end }}
    # Allow prometheus scrapes
    - ports:
        - port: {{ .Values.service.ports.metrics }}
{{- end }}
