apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-headless
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
<<<<<<< HEAD
  {{- if or (.Values.service.annotationsHeadless) (.Values.commonAnnotations) }}
  annotations:
    {{- if .Values.commonAnnotations}}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end -}}
    {{- if .Values.service.annotationsHeadless}}
=======
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.service.annotationsHeadless .Values.commonAnnotations }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end -}}
    {{- if .Values.service.annotationsHeadless }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
    {{- include "common.tplvalues.render" (dict "value" .Values.service.annotationsHeadless "context" $) | nindent 4 }}
    {{- end -}}
  {{- end }}
spec:
  clusterIP: None
  ports:
    - name: {{ .Values.service.portNames.epmd }}
      port: {{ .Values.service.ports.epmd }}
      targetPort: epmd
    {{- if or (.Values.service.portEnabled) (not .Values.auth.tls.enabled) }}
<<<<<<< HEAD
    - name: amqp
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName }}
=======
    - name: {{ .Values.service.portNames.amqp }}
      port: {{ .Values.service.ports.amqp }}
      targetPort: amqp
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
    {{- end }}
    {{- if .Values.auth.tls.enabled }}
    - name: {{ .Values.service.portNames.amqpTls }}
      port: {{ .Values.service.ports.amqpTls }}
      targetPort: amqp-tls
    {{- end }}
    - name: {{ .Values.service.portNames.dist }}
      port: {{ .Values.service.ports.dist }}
      targetPort: dist
    {{- if .Values.service.managerPortEnabled }}
    - name: {{ .Values.service.portNames.manager }}
      port: {{ .Values.service.ports.manager  }}
      targetPort: stats
    {{- end }}
  selector: {{ include "common.labels.matchLabels" . | nindent 4 }}
  publishNotReadyAddresses: true
