apiVersion: v1
kind: Service
metadata:
  name: {{ template "grafana-tempo.gossip-ring.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: tempo
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.tempo.gossipRing.service.annotations }}
  annotations:
    {{- if .Values.tempo.gossipRing.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.tempo.gossipRing.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - name: http
<<<<<<< HEAD
      port: {{ .Values.tempo.gossipRing.service.port }}
=======
      port: {{ .Values.tempo.gossipRing.service.ports.http }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
      targetPort: http-memberlist
      protocol: TCP
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    tempo-gossip-member: "true"
