{{- if .Values.proxy.pdb.create -}}
<<<<<<< HEAD
apiVersion: policy/v1beta1
=======
apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
kind: PodDisruptionBudget
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: proxy
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: {{ include "jupyterhub.proxy.name" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  minAvailable: {{ .Values.proxy.pdb.minAvailable }}
  maxUnavailable: {{ .Values.proxy.pdb.maxUnavailable }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: proxy
{{- end }}
