apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
=======
  name: {{ printf "%s-proxy-api" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: proxy
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
<<<<<<< HEAD
  name: {{ printf "%s-proxy-api" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.proxy.service.api.type }}
  {{- if (or (eq .Values.proxy.service.api.type "LoadBalancer") (eq .Values.proxy.service.api.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.proxy.service.api.externalTrafficPolicy | quote }}
  {{- end }}
  {{ if eq .Values.proxy.service.api.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.proxy.service.api.loadBalancerSourceRanges }}
  {{ end }}
  {{- if (and (eq .Values.proxy.service.api.type "LoadBalancer") (not (empty .Values.proxy.service.api.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.proxy.service.api.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.proxy.service.api.port }}
=======
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.proxy.service.api.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.proxy.service.api.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.proxy.service.api.type }}
  {{- if and .Values.proxy.service.api.clusterIP (eq .Values.proxy.service.api.type "ClusterIP") }}
  clusterIP: {{ .Values.proxy.service.api.clusterIP }}
  {{- end }}
  {{- if or (eq .Values.proxy.service.api.type "LoadBalancer") (eq .Values.proxy.service.api.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.proxy.service.api.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.proxy.service.api.type "LoadBalancer") (not (empty .Values.proxy.service.api.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.proxy.service.api.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.proxy.service.api.type "LoadBalancer") (not (empty .Values.proxy.service.api.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.proxy.service.api.loadBalancerIP }}
  {{- end }}
  {{- if .Values.proxy.service.api.sessionAffinity }}
  sessionAffinity: {{ .Values.proxy.service.api.sessionAffinity }}
  {{- end }}
  {{- if .Values.proxy.service.api.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.proxy.service.api.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: {{ coalesce .Values.proxy.service.api.ports.http .Values.proxy.service.api.port }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
      targetPort: api
      protocol: TCP
      {{- if (and (or (eq .Values.proxy.service.api.type "NodePort") (eq .Values.proxy.service.api.type "LoadBalancer")) (not (empty .Values.proxy.service.api.nodePorts.http))) }}
      nodePort: {{ .Values.proxy.service.api.nodePorts.http }}
      {{- else if eq .Values.proxy.service.api.type "ClusterIP" }}
      nodePort: null
      {{- end }}
<<<<<<< HEAD
=======
    {{- if .Values.proxy.service.api.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.proxy.service.api.extraPorts "context" $) | nindent 4 }}
    {{- end }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
