annotations:
  category: Database
apiVersion: v2
<<<<<<< HEAD
appVersion: 4.4.8
=======
appVersion: 6.0.1
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: MongoDB(R) is a relational open source NoSQL database. Easy to use, it stores data in JSON-like documents. Automated scalability and high-performance. Ideal for developing cloud native applications.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/mongodb
icon: https://bitnami.com/assets/stacks/mongodb/img/mongodb-stack-220x234.png
keywords:
  - mongodb
  - database
  - nosql
  - cluster
  - replicaset
  - replication
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: mongodb
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/mongodb
  - https://mongodb.org
<<<<<<< HEAD
version: 10.25.1
=======
version: 13.1.0
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
