{{- if (include "keycloak.createConfigmap" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configuration" (include "keycloak.fullname" .) }}
<<<<<<< HEAD
  namespace: {{ .Release.Namespace }}
=======
  namespace: {{ include "common.names.namespace" . | quote }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
<<<<<<< HEAD
  standalone-ha.xml: |-
=======
  keycloak.conf: |-
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
    {{- .Values.configuration | nindent 4 }}
{{- end }}
