{{ if .Values.singleuser.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
<<<<<<< HEAD
=======
  name: {{ template "jupyterhub.singleuserServiceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: singleuser
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
<<<<<<< HEAD
  name: {{ template "jupyterhub.singleuserServiceAccountName" . }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace | quote }}
=======
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.singleuser.serviceAccount.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.singleuser.serviceAccount.annotations "context" $ ) | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.singleuser.serviceAccount.automountServiceAccountToken }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
{{- end }}
