{{- if .Values.webhook.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
<<<<<<< HEAD
automountServiceAccountToken: true
=======
automountServiceAccountToken: {{ .Values.webhook.serviceAccount.automountServiceAccountToken }}
>>>>>>> ee2009506fa88a29a08be8ffce1bb6753a5ab4d0
metadata:
  labels:
    app.kubernetes.io/component: webhook
  {{- include "common.labels.standard" . | nindent 4 }}
  name: {{ template "certmanager.webhook.serviceAccountName" . }}
  {{- $mergedAnnotations := merge .Values.webhook.serviceAccount.annotations .Values.commonAnnotations }}
  {{- if $mergedAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $mergedAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
